/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Archivo;
import Clases.ConectarBase;
import Clases.Conexion;
import Clases.ConsultasObjetos;
import Controlador.ControladorHorarios;
import Objetos.Grupo;
import Objetos.Licenciatura;
import Objetos.Materia;
import Objetos.PeriodoHorarios;
import Objetos.Profesor;
import Objetos.periodoEscolar;
import cjb.ci.Mensaje;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JeanCarlos
 */
public class VistaExcel extends javax.swing.JFrame {

    /**
     * Creates new form VistaExcel
     */
    public VistaExcel() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    File archivo;
    int numcorreo = 0;
    String cabeceras[];
    String tipoExcel = "";
    String cabecerasProfesor[] = {"rfc", "apellido paterno", "apellido materno", "nombre", "grado academico", "correo", "telefono"};
    String cabecerasMateria[] = {"clave de la materia", "unidad de aprendizaje", "horas", "creditos", "numero de periodo", "nucleo", "tipo", "licenciatura", "plan de estudios"};
    String cabecerasHorario[] = {"clave materia", "unidad de aprendizaje", "rfc", "profesor", "grupo", "periodo", "dia", "entrada", "salida"};
    ArrayList<Profesor> profes;
    ArrayList<Materia> materias;
    ArrayList<Grupo> grupos;
    ArrayList<Licenciatura> carreras;
    ArrayList<periodoEscolar> periodos;
    ArrayList<PeriodoHorarios> horarios;
    ArrayList<PeriodoHorarios> horariosBD;

    private File abrirArchivo() {
        String aux = "";
        String texto = "";
        String nombre = "";
        File abre = null;

        try {
            /**
             * llamamos el metodo que permite cargar la ventana
             */
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            nombre = file.getSelectedFile().getName();
            /**
             * abrimos el archivo seleccionado
             */

            abre = file.getSelectedFile();
            //Archivo.AbreArchivoV1(abre);
            return abre;
//
//            /**
//             * recorremos el archivo, lo leemos para plasmarlo en el area de texto
//             */
//            if (abre != null) {
//                FileReader archivos = new FileReader(abre);
//                BufferedReader lee = new BufferedReader(archivos);
//                while ((aux = lee.readLine()) != null) {
//                    texto += aux + "\n";
//                }
//                lee.close();
//            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
        return abre;
        //El texto se almacena en el JTextArea
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatosExcel = new javax.swing.JTable();
        btnCarga = new javax.swing.JButton();
        txtidentifica = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDatosNoEncontrados = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcruzesExcel = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCruzeMaterias = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtCruzeProfesores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCheckLllaves = new javax.swing.JCheckBox();
        jCheckMateriasBD = new javax.swing.JCheckBox();
        jCheckProfesores = new javax.swing.JCheckBox();
        jCheckExcel = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnImportar.setBackground(new java.awt.Color(102, 102, 0));
        btnImportar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImportar.setForeground(new java.awt.Color(255, 255, 255));
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        jTDatosExcel.setBackground(new java.awt.Color(25, 83, 0));
        jTDatosExcel.setForeground(new java.awt.Color(255, 255, 255));
        jTDatosExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTDatosExcel);

        btnCarga.setBackground(new java.awt.Color(102, 102, 0));
        btnCarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnCarga.setText("Cargar");
        btnCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaActionPerformed(evt);
            }
        });

        txtidentifica.setText("No identificado");

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar Celda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Ejectuar Pruebas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtDatosNoEncontrados.setColumns(20);
        txtDatosNoEncontrados.setRows(5);
        jScrollPane2.setViewportView(txtDatosNoEncontrados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DATOS NO ENCONTRADOS", jPanel2);

        txtcruzesExcel.setColumns(20);
        txtcruzesExcel.setRows(5);
        jScrollPane3.setViewportView(txtcruzesExcel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("HORARIOS CRUZADOS EN EXCEL", jPanel3);

        txtCruzeMaterias.setColumns(20);
        txtCruzeMaterias.setRows(5);
        jScrollPane4.setViewportView(txtCruzeMaterias);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ERRORES CON MATERIAS", jPanel4);

        txtCruzeProfesores.setColumns(20);
        txtCruzeProfesores.setRows(5);
        jScrollPane5.setViewportView(txtCruzeProfesores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ERRORES CON PROFESORES", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RESULTADO DE PRUEBAS");

        jPanel5.setBackground(new java.awt.Color(25, 83, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jCheckLllaves.setForeground(new java.awt.Color(255, 255, 255));
        jCheckLllaves.setText("DATOS CORRECTOS EN EXCEL");

        jCheckMateriasBD.setForeground(new java.awt.Color(255, 255, 255));
        jCheckMateriasBD.setText("MATERIAS CURZADAS");

        jCheckProfesores.setForeground(new java.awt.Color(255, 255, 255));
        jCheckProfesores.setText("PROFESORES CRUZADOS ");

        jCheckExcel.setForeground(new java.awt.Color(255, 255, 255));
        jCheckExcel.setText("HORARIOS CRUZADOS EN EL EXCEL");
        jCheckExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckLllaves)
                    .addComponent(jCheckExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckMateriasBD)
                    .addComponent(jCheckProfesores))
                .addGap(86, 86, 86))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckLllaves)
                    .addComponent(jCheckMateriasBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckExcel)
                    .addComponent(jCheckProfesores))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtidentifica, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane1)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnImportar)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCarga))
                                .addGap(27, 27, 27)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(txtidentifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        limpiaDatos();
        btnCarga.setEnabled(false);
        archivo = abrirArchivo();
        Archivo.Importar(archivo, jTDatosExcel);
        cabeceras = new String[jTDatosExcel.getColumnCount()];
        for (int i = 0; i < jTDatosExcel.getColumnCount(); i++) {
            cabeceras[i] = jTDatosExcel.getColumnName(i);
        }
        tipoExcel = identifica();
        txtidentifica.setText(tipoExcel);

    }//GEN-LAST:event_btnImportarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        limpiaDatos();
        txtCruzeMaterias.setEditable(false);
        txtCruzeProfesores.setEditable(false);
        txtDatosNoEncontrados.setEditable(false);
        txtcruzesExcel.setEditable(false);
        txtidentifica.setEditable(false);
        btnCarga.setEnabled(false);
        jCheckExcel.setEnabled(false);
        jCheckLllaves.setEnabled(false);
        jCheckMateriasBD.setEnabled(false);
        jCheckProfesores.setEnabled(false);


        importaBD();
        //muestraBD();
        ordenamientoBurbujaID("licenciatura");
        ordenamientoBurbujaNombre("materia");
        ordenamientoBurbujaNombre("grupo");
        muestraBD();

        System.out.println("Busqueda " + busquedaBinariaRetID("INGENIERIA EN COMPUTACION", "licenciatura"));
        System.out.println("Busqueda " + busquedaBinariaRetNombre(6, "licenciatura"));

        System.out.println("Busqueda " + busquedaBinariaRetID("s2", "grupo"));
        System.out.println("Busqueda " + busquedaBinariaRetNombre(2, "grupo"));
        //txtidentifica.setForeground(Color.red);
        


    }//GEN-LAST:event_formWindowOpened

    public void limpiaDatos(){
        txtCruzeMaterias.setText("");
        txtCruzeProfesores.setText("");
        txtDatosNoEncontrados.setText("");
        txtcruzesExcel.setText("");
        jCheckExcel.setSelected(false);
        jCheckLllaves.setSelected(false);
        jCheckMateriasBD.setSelected(false);
        jCheckProfesores.setSelected(false);
    }
    public ArrayList<Object> extraeDatos() {
        ArrayList profesores = new ArrayList();

        for (int i = 0; i < jTDatosExcel.getRowCount(); i++) {
            Profesor profe = new Profesor();
            profe.setRfc(String.valueOf(jTDatosExcel.getValueAt(i, 1)));
            System.out.println(String.valueOf(jTDatosExcel.getValueAt(i, 1)));
            profe.setNombres((String) jTDatosExcel.getValueAt(i, 4));
            profe.setApellidoP((String) jTDatosExcel.getValueAt(i, 2));
            profe.setApellidoM((String) jTDatosExcel.getValueAt(i, 3));
            profe.setCorreo("no ingresado" + String.valueOf(numcorreo++));
            profe.setTelefono((String) jTDatosExcel.getValueAt(i, 7));
            profe.setGradoAcademico((String) jTDatosExcel.getValueAt(i, 3));
            profesores.add(profe);
        }
        return profesores;
    }

    public String identifica() {
        boolean identificado = false;
        if (cabeceras.length == cabecerasProfesor.length) {
            for (int i = 0; i < cabeceras.length; i++) {
                if (!cabeceras[i].equalsIgnoreCase(cabecerasProfesor[i])) {
                    break;
                }
            }
            txtDatosNoEncontrados.setText("Es un profesor");
            identificado = true;
            return "profesor";

        }
        if (cabeceras.length == cabecerasMateria.length && identificado) {
            for (int i = 0; i < cabeceras.length; i++) {
                if (!cabeceras[i].equalsIgnoreCase(cabecerasMateria[i])) {
                    break;
                }
            }
            identificado = true;
            return "materia";
        }

        if (cabeceras.length == cabecerasHorario.length) {
            for (int i = 0; i < cabeceras.length; i++) {
                if (!cabeceras[i].equalsIgnoreCase(cabecerasHorario[i])) {
                    break;
                }
            }
            identificado = true;
            return "horario";
        }
        if (!identificado) {
            return "No es encontro el tipo de excel";
        }
        return null;
    }
    private void btnCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaActionPerformed

        ArrayList horarios = guardaExcel();
        ConsultasObjetos.insertaMuchos(horarios, ConectarBase.conectado(), "horarios");
        //        if (String.valueOf(jcTipo.getSelectedItem()).equals("Profesor")) {
//            
//        }
//            ArrayList<Object> profes= extraeDatos();
//            System.out.println(Controlador.ControladorProfesores.insertaMuchos(profes));
//txtconsulta.setText(ConsultasObjetos.retornaConsulta(profes, ConectarBase.conectado(), "profesores"));
//ConsultasObjetos.insertaMuchos(profes, ConectarBase.conectado(), "profesores");

    }//GEN-LAST:event_btnCargaActionPerformed

    public ArrayList guardaExcel() {

        if (tipoExcel.equalsIgnoreCase("horario")) {
            System.out.println("Entrando a horario");
            ArrayList horarios = new ArrayList();
            PeriodoHorarios horario;
            

            for (int i = 0; i < jTDatosExcel.getRowCount(); i++) {
                horario = new PeriodoHorarios();
                horario.setClaveMateria(String.valueOf(jTDatosExcel.getValueAt(i, 0)));
                horario.setRfc(String.valueOf(String.valueOf(jTDatosExcel.getValueAt(i, 2))));
                if (ControladorHorarios.numdia(String.valueOf(jTDatosExcel.getValueAt(i, 6))) != 0) {
                    horario.setDia(String.valueOf(ControladorHorarios.numdia(String.valueOf(jTDatosExcel.getValueAt(i, 6)))));
                }
                horario.setIdGrupo(String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 4)), "grupo")));
                horario.setIdPeriodo(String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 5)), "periodo")));
                horario.setEntrada(String.valueOf(jTDatosExcel.getValueAt(i, 7)));
                horario.setSalida(String.valueOf(jTDatosExcel.getValueAt(i, 8)));
                horarios.add(horario);
                muestraHorarios(horario);
            }
            ordenamientoBurbujaID("grupo");
            return horarios;
        }
        return null;
    }

    public void importaBD() {
        materias = new ArrayList(ConsultasObjetos.consultaMuchos("materia", null, null, null, null, null, ConectarBase.conectado()));
        profes = new ArrayList(ConsultasObjetos.consultaMuchos("profesores", null, null, null, null, null, ConectarBase.conectado()));
        grupos = new ArrayList(ConsultasObjetos.consultaMuchos("grupo", null, null, null, null, null, ConectarBase.conectado()));
        carreras = new ArrayList(ConsultasObjetos.consultaMuchos("licenciatura", null, null, null, null, null, ConectarBase.conectado()));
        periodos = new ArrayList(ConsultasObjetos.consultaMuchos("periodo_escolar", null, null, null, null, null, ConectarBase.conectado()));
    }

    public void muestraBD() {
        for (Object materia : materias) {
            System.out.println(((Materia) materia).getUnidadAprendizaje());
        }
//        for (Object profesor : profes){
//            System.out.println(((Profesor)profesor).getNombres());
//        }
        for (Object grupo : grupos) {
            System.out.println(((Grupo) grupo).getNombreGrupo());
        }
        for (Object licen : carreras) {
            System.out.println(((Licenciatura) licen).getLicenciatura());
        }
        for (Object periodo : periodos) {
            System.out.println(((periodoEscolar) periodo).getPeriodo());
        }
    }

    public void transforma() {

    }


    public boolean comparaMateriasExcel() {
        boolean prueba = true;
        double entrada1, salida1, entrada2, salida2;
        String mensaje = "";
        for (int i = 0; i < horarios.size(); i++) {
            for (int j = 0; j < horarios.size(); j++) {
                //System.out.println("dia: "+horarios.get(i).getDia() + " ---->"+ "dia: "+horarios.get(j).getDia() );
                if (horarios.get(i).getDia().equals(horarios.get(j).getDia()) && i != j 
                        //&& horarios.get(i).getIdGrupo().equals(horarios.get(j).getIdGrupo())
                        //&& horarios.get(i).getClaveMateria().equals(horarios.get(j).getClaveMateria())
                        && horarios.get(i).getRfc().equals(horarios.get(j).getRfc())) {
                    //System.out.println("Mismo dia ");
                    //System.out.println(horarios.get(i).getClaveMateria() + " " + horarios.get(i).getRfc() + " " + horarios.get(i).getIdPeriodo());
                    //System.out.println(horarios.get(j).getClaveMateria() + " " + horarios.get(j).getRfc() + " " + horarios.get(j).getIdPeriodo());
                    entrada1 = Double.parseDouble(horarios.get(i).getEntrada().substring(0, 2) + "." + horarios.get(i).getEntrada().substring(3, 5));
                    salida1 = Double.parseDouble(horarios.get(i).getSalida().substring(0, 2) + "." + horarios.get(i).getSalida().substring(3, 5));
                    entrada2 = Double.parseDouble(horarios.get(j).getEntrada().substring(0, 2) + "." + horarios.get(j).getEntrada().substring(3, 5));
                    salida2 = Double.parseDouble(horarios.get(j).getSalida().substring(0, 2) + "." + horarios.get(j).getSalida().substring(3, 5));
                    if (entrada2 >= entrada1 && entrada2 < salida1) {
                        
                        prueba = false;
                        mensaje += "Cruze de Profesor\n"
                                + "Materia: " + String.valueOf(jTDatosExcel.getValueAt(i, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 1))+"\n"
                                + "Profesor " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 3)) + "\n"
                                + "Grupo: " +  String.valueOf(jTDatosExcel.getValueAt(i, 4)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 4))+"\n"
                                + "Dia: " +  String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j,6))+"\n"
                                + "Horario: " +  String.valueOf(jTDatosExcel.getValueAt(i, 7)) +" - " +String.valueOf(jTDatosExcel.getValueAt(i, 8)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j,7)) +"- "+ String.valueOf(jTDatosExcel.getValueAt(j,8))+"\n\n";
                                
                             //   + String.valueOf(jTDatosExcel.getValueAt(i, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 4))+String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 7)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 8))
                              //  + " y "
                               // + String.valueOf(jTDatosExcel.getValueAt(j, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 4)) + " " +String.valueOf(jTDatosExcel.getValueAt(i, 3))+ String.valueOf(jTDatosExcel.getValueAt(j, 7)) + " " + String.valueOf(jTDatosExcel.getValueAt(j, 8)) + "\n\n";
                        //System.out.println("horarios cruzados");
                    }
                    
                    
                }
                
                if (horarios.get(i).getDia().equals(horarios.get(j).getDia()) && i != j 
                        && horarios.get(i).getIdGrupo().equals(horarios.get(j).getIdGrupo())){
                        //&& horarios.get(i).getClaveMateria().equals(horarios.get(j).getClaveMateria())){
                        //&& horarios.get(i).getRfc().equals(horarios.get(j).getRfc())) {
                    //System.out.println("Mismo dia ");
                    //System.out.println(horarios.get(i).getClaveMateria() + " " + horarios.get(i).getRfc() + " " + horarios.get(i).getIdPeriodo());
                    //System.out.println(horarios.get(j).getClaveMateria() + " " + horarios.get(j).getRfc() + " " + horarios.get(j).getIdPeriodo());
                    entrada1 = Double.parseDouble(horarios.get(i).getEntrada().substring(0, 2) + "." + horarios.get(i).getEntrada().substring(3, 5));
                    salida1 = Double.parseDouble(horarios.get(i).getSalida().substring(0, 2) + "." + horarios.get(i).getSalida().substring(3, 5));
                    entrada2 = Double.parseDouble(horarios.get(j).getEntrada().substring(0, 2) + "." + horarios.get(j).getEntrada().substring(3, 5));
                    salida2 = Double.parseDouble(horarios.get(j).getSalida().substring(0, 2) + "." + horarios.get(j).getSalida().substring(3, 5));
                    if (entrada2 >= entrada1 && entrada2 < salida1) {
                        
                        prueba = false;
                        mensaje += "Cruze del mismo Grupo\n"
                                + "Materia: " + String.valueOf(jTDatosExcel.getValueAt(i, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 1))+"\n"
                                + "Profesor " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 3)) + "\n"
                                + "Grupo: " +  String.valueOf(jTDatosExcel.getValueAt(i, 4)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 4))+"\n"
                                + "Dia: " +  String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j,6))+"\n"
                                + "Horario: " +  String.valueOf(jTDatosExcel.getValueAt(i, 7)) +" - " +String.valueOf(jTDatosExcel.getValueAt(i, 8)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j,7)) +"- "+ String.valueOf(jTDatosExcel.getValueAt(j,8))+"\n\n";
                                
                             //   + String.valueOf(jTDatosExcel.getValueAt(i, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 4))+String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 7)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 8))
                              //  + " y "
                               // + String.valueOf(jTDatosExcel.getValueAt(j, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 4)) + " " +String.valueOf(jTDatosExcel.getValueAt(i, 3))+ String.valueOf(jTDatosExcel.getValueAt(j, 7)) + " " + String.valueOf(jTDatosExcel.getValueAt(j, 8)) + "\n\n";
                        //System.out.println("horarios cruzados");
                    }
                    
                    
                }
            }
        }
        txtcruzesExcel.setText(mensaje);
        return prueba;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTDatosExcel.getSelectedRow() != -1) {
            ((DefaultTableModel) jTDatosExcel.getModel()).removeRow(jTDatosExcel.getSelectedRow());
        } else {
            Mensaje.error(this, "No se pudo eliminar la celda");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiaDatos();
        if (tipoExcel.equalsIgnoreCase("horario")) {
            horariosBD = new ArrayList(ConsultasObjetos.consultaMuchos("horarios", null, null, null, null, null, ConectarBase.conectado()));
            horarios = guardaExcel();
            System.out.println("");
            jCheckLllaves.setSelected(validaExcel());
            jCheckExcel.setSelected(comparaMateriasExcel());
            if (jCheckLllaves.isSelected()) {
                
                jCheckProfesores.setSelected(evaluaProfesores());
                jCheckMateriasBD.setSelected(evaluaGruposBD());
                
            }

            if (jCheckExcel.isSelected() && jCheckProfesores.isSelected() && jCheckMateriasBD.isSelected() && jCheckLllaves.isSelected()) {
                btnCarga.setEnabled(true);
                Mensaje.exito(this, "Se han pasado todas las pruebas");
            } else {
                btnCarga.setEnabled(false);
                Mensaje.error(this, "Alguna prueba no ha sido superada");
            }

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckExcelActionPerformed

    public boolean evaluaProfesores() {
        boolean prueba = true;
        double entrada1, entrada2, salida1, salida2;
        String mensaje = "";
        for (int i = 0; i < horarios.size(); i++) {
            for (int j = 0; j < horariosBD.size(); j++) {
                System.out.println("i: " + i);
                System.out.println("j: " + j);
                if (horarios.get(i).getRfc().equalsIgnoreCase(horariosBD.get(j).getRfc()) && horarios.get(i).getDia().equals(horariosBD.get(j).getDia())) {

                    entrada1 = Double.parseDouble(horarios.get(i).getEntrada().substring(0, 2) + "." + horarios.get(i).getEntrada().substring(3, 5));
                    salida1 = Double.parseDouble(horarios.get(i).getSalida().substring(0, 2) + "." + horarios.get(i).getSalida().substring(3, 5));
                    entrada2 = Double.parseDouble(horariosBD.get(j).getEntrada().substring(0, 2) + "." + horariosBD.get(j).getEntrada().substring(3, 5));
                    salida2 = Double.parseDouble(horariosBD.get(j).getSalida().substring(0, 2) + "." + horariosBD.get(j).getSalida().substring(3, 5));
                    System.out.println("horario1 " + entrada1 + " " + salida1);
                    System.out.println("horario2 " + entrada2 + " " + salida2);
                    System.out.println("mismo dia ");
                    if (entrada2 >= entrada1 && entrada2 <= salida1) {
                        prueba = false;
                        
                        mensaje += "Cruze de Profesores\n"
                                + "Materia: " + String.valueOf(jTDatosExcel.getValueAt(i, 1))  + " -> " + busquedaBinariaRetNombre(horariosBD.get(j).getClaveMateria(), "materias")+"\n"
                                + "Profesor: " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " -> " + busquedaBinariaRetNombre(horariosBD.get(j).getRfc(), "profesores")  + "\n"
                                + "Grupo: " +  String.valueOf(jTDatosExcel.getValueAt(i, 4))  + "->"+busquedaBinariaRetNombre(Integer.valueOf(horariosBD.get(j).getIdGrupo()), "grupo") + "\n"
                                + "Dia: " +  String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " -> " + ControladorHorarios.numdia(Integer.valueOf(horariosBD.get(j).getDia()))+"\n"
                                + "Horario: "  + String.valueOf(jTDatosExcel.getValueAt(i, 7)) + " - " + String.valueOf(jTDatosExcel.getValueAt(i, 8)) + " -> " + horariosBD.get(j).getEntrada().substring(0,5) + " " + horariosBD.get(j).getSalida().substring(0,5) + "\n\n";
                        
                        
                        
//                        mensaje += "Error Por Profesores\n"
//                                + String.valueOf(jTDatosExcel.getValueAt(i, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 7)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 8))
//                                + " y "+"\n"
//                                + busquedaBinariaRetNombre(horariosBD.get(j).getClaveMateria(), "materias") + "-> " + ControladorHorarios.numdia(Integer.valueOf(horariosBD.get(j).getDia())) + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida() + "\n\n";

                        System.out.println("Profesor: " + String.valueOf(jTDatosExcel.getValueAt(i, 2)) + "cruzado " + horarios.get(i).getDia() + " " + horarios.get(i).getEntrada() + " " + horarios.get(i).getSalida());
                        System.out.println("Con id: " + horariosBD.get(j).getIdHorario() + " " + horariosBD.get(j).getDia() + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida());

                        //txtconsulta.setText(txtconsulta.getText() + "Error en Grupos: " + String.valueOf(jTDatosExcel.getValueAt(i, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " y " + String.valueOf(jTDatosExcel.getValueAt(j, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + "\n\n");
                        //System.out.println("horarios cruzados");
                    }

//                    System.out.println("ProfesorLoc:" + horarios.get(i).getDia() + " " + horarios.get(i).getEntrada() + " " + horarios.get(i).getSalida());
//                    System.out.println("ProfesorBD:" + horariosBD.get(j).getDia() + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida());
                }
            }
        }
        txtCruzeProfesores.setText(mensaje);
        return prueba;
    }

    public boolean evaluaGruposBD() {
        boolean prueba = true;
        double entrada1, entrada2, salida1, salida2;
        String mensaje = "";
        for (int i = 0; i < horarios.size(); i++) {
            for (int j = 0; j < horariosBD.size(); j++) {
                if (horarios.get(i).getClaveMateria().equalsIgnoreCase(horariosBD.get(j).getClaveMateria()) && horarios.get(i).getDia().equalsIgnoreCase(horariosBD.get(j).getDia())
                        && horarios.get(i).getIdGrupo().equals(horariosBD.get(j).getIdGrupo())) {
                    entrada1 = Double.parseDouble(horarios.get(i).getEntrada().substring(0, 2) + "." + horarios.get(i).getEntrada().substring(3, 5));
                    salida1 = Double.parseDouble(horarios.get(i).getSalida().substring(0, 2) + "." + horarios.get(i).getSalida().substring(3, 5));
                    entrada2 = Double.parseDouble(horariosBD.get(j).getEntrada().substring(0, 2) + "." + horariosBD.get(j).getEntrada().substring(3, 5));
                    salida2 = Double.parseDouble(horariosBD.get(j).getSalida().substring(0, 2) + "." + horariosBD.get(j).getSalida().substring(3, 5));
                    if (entrada2 >= entrada1 && entrada2 <= salida1) {
                        prueba = false;
                        mensaje += "Cruze de Materia\n"
                                + "Materia: " + String.valueOf(jTDatosExcel.getValueAt(i, 1))  + " -> " + busquedaBinariaRetNombre(horariosBD.get(j).getClaveMateria(), "materias")+"\n"
                                + "Profesor " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " -> " + busquedaBinariaRetNombre(horariosBD.get(j).getRfc(), "profesores")  + "\n"
                                + "Grupo: " +  String.valueOf(jTDatosExcel.getValueAt(i, 4))  + busquedaBinariaRetNombre(Integer.valueOf(horariosBD.get(j).getIdGrupo()), "grupo") + "\n"
                                + "Dia: " +  String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " -> " + ControladorHorarios.numdia(Integer.valueOf(horariosBD.get(j).getDia()))+"\n"
                                + "Horario: "  + String.valueOf(jTDatosExcel.getValueAt(i, 7)) + " - " + String.valueOf(jTDatosExcel.getValueAt(i, 8)) + " -> " + horariosBD.get(j).getEntrada().substring(0,5) + " " + horariosBD.get(j).getSalida().substring(0,5) + "\n\n";
                        
                        
//                        mensaje += "Error en materia BD\n"
//                                + String.valueOf(jTDatosExcel.getValueAt(i, 1)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 7)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 8))
//                                + " y "
//                                + busquedaBinariaRetNombre(horariosBD.get(j).getClaveMateria(), "materias") + "-> " + ControladorHorarios.numdia(Integer.valueOf(horariosBD.get(j).getDia())) + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida() + "\n\n";
                        //System.out.println("Profesor: " + String.valueOf(jTDatosExcel.getValueAt(i, 2)) + "cruzado " + horarios.get(i).getDia() + " " + horarios.get(i).getEntrada() + " " + horarios.get(i).getSalida());
                        //System.out.println("Con id: " + horariosBD.get(j).getIdHorario() + " " + horariosBD.get(j).getDia() + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida());

                        //txtconsulta.setText(txtconsulta.getText() + "Error en Grupos: " + String.valueOf(jTDatosExcel.getValueAt(i, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " y " + String.valueOf(jTDatosExcel.getValueAt(j, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + "\n\n");
                        //System.out.println("horarios cruzados");
                    }

//                    System.out.println("ProfesorLoc:" + horarios.get(i).getDia() + " " + horarios.get(i).getEntrada() + " " + horarios.get(i).getSalida());
//                    System.out.println("ProfesorBD:" + horariosBD.get(j).getDia() + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida());
                }
            }
        }
        txtCruzeMaterias.setText(mensaje);
        return prueba;
    }

    public boolean validaExcel() {
        boolean prueba = true;
        double entrada1, entrada2, salida1, salida2;
        String mensaje = "";
        ordenamientoBurbujaID("materia");
        ordenamientoBurbujaNombre("grupo");
        for (int i = 0; i < horarios.size(); i++) {
            System.out.println("registro " + i);
            if (busquedaBinariaBuscaID(String.valueOf(jTDatosExcel.getValueAt(i, 0)), "materia") == null) {
                prueba = false;
                mensaje += "Materia: " + String.valueOf(jTDatosExcel.getValueAt(i, 0) + " NO ENCONTRADO") + "\n\n";
                //System.out.println("Materia no encontrado");
            }
            if (busquedaBinariaBuscaID(String.valueOf(jTDatosExcel.getValueAt(i, 2)), "profesor") == null) {
                prueba = false;
                mensaje += "Profesor: " + String.valueOf(jTDatosExcel.getValueAt(i, 2) + " NO ENCONTRADO") + "\n\n";
                System.out.println("profesor no encontrado");
            }
            if (busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 4)), "grupo") == -1) {
                prueba = false;
                mensaje += "Grupo: " + String.valueOf(jTDatosExcel.getValueAt(i, 4) + " NO ENCONTRADO") + "\n\n";
                System.out.println("Grupos no encontrado" + i);
            }
            if (busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 5)), "periodo") == -1) {
                prueba = false;
                mensaje += "Periodo: " + String.valueOf(jTDatosExcel.getValueAt(i, 5) + " NO ENCONTRADO") + "\n\n";
                //System.out.println("periodo no encontrado");
            }
        }
        txtDatosNoEncontrados.setText(mensaje);
        return prueba;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaExcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarga;
    public javax.swing.JButton btnImportar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckExcel;
    private javax.swing.JCheckBox jCheckLllaves;
    private javax.swing.JCheckBox jCheckMateriasBD;
    private javax.swing.JCheckBox jCheckProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTDatosExcel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtCruzeMaterias;
    private javax.swing.JTextArea txtCruzeProfesores;
    private javax.swing.JTextArea txtDatosNoEncontrados;
    private javax.swing.JTextArea txtcruzesExcel;
    private javax.swing.JTextField txtidentifica;
    // End of variables declaration//GEN-END:variables

    public void ordenamientoBurbujaID(String tipo) {
        switch (tipo) {
            case "grupo":
                Grupo grup;
                for (int i = 1; i < grupos.size(); i++) {
                    for (int j = 0; j < grupos.size() - i; j++) {
                        if (Integer.valueOf(grupos.get(j).getIdGrupo()) > Integer.valueOf(grupos.get(j + 1).getIdGrupo())) {
                            grup = grupos.get(j);
                            grupos.set(j, grupos.get(j + 1));
                            grupos.set(j + 1, grup);
                        }
                    }
                }
                break;
            case "licenciatura":
                Licenciatura lic;
                for (int i = 1; i < carreras.size(); i++) {
                    for (int j = 0; j < carreras.size() - i; j++) {
                        if (carreras.get(j).getIdLicenciatura().compareToIgnoreCase(carreras.get(j + 1).getIdLicenciatura()) > 0) {
                            lic = carreras.get(j);
                            carreras.set(j, carreras.get(j + 1));
                            carreras.set(j + 1, lic);
                        }
                    }
                }
                break;

            case "materia":
                Materia mat;
                for (int i = 1; i < materias.size(); i++) {
                    for (int j = 0; j < materias.size() - i; j++) {
                        if (materias.get(j).getClaveMateria().compareToIgnoreCase(materias.get(j + 1).getClaveMateria()) > 0) {
                            mat = materias.get(j);
                            materias.set(j, materias.get(j + 1));
                            materias.set(j + 1, mat);
                        }
                    }
                }

                break;
        }
    }

    public void ordenamientoBurbujaNombre(String tipo) {
        switch (tipo) {
            case "grupo":
                Grupo grup;
                for (int i = 1; i < grupos.size(); i++) {
                    for (int j = 0; j < grupos.size() - i; j++) {
                        if (grupos.get(j).getNombreGrupo().compareToIgnoreCase(grupos.get(j + 1).getNombreGrupo()) > 0) {
                            grup = grupos.get(j);
                            grupos.set(j, grupos.get(j + 1));
                            grupos.set(j + 1, grup);
                        }
                    }
                }
                break;
            //esta por id
            case "licenciatura":
                Licenciatura lic;
                for (int i = 1; i < carreras.size(); i++) {
                    for (int j = 0; j < carreras.size() - i; j++) {
                        if (carreras.get(j).getIdLicenciatura().compareToIgnoreCase(carreras.get(j + 1).getIdLicenciatura()) > 0) {
                            lic = carreras.get(j);
                            carreras.set(j, carreras.get(j + 1));
                            carreras.set(j + 1, lic);
                        }
                    }
                }
                break;

            case "materia":
                Materia mat;
                for (int i = 1; i < materias.size(); i++) {
                    for (int j = 0; j < materias.size() - i; j++) {
                        if (materias.get(j).getUnidadAprendizaje().compareToIgnoreCase(materias.get(j + 1).getUnidadAprendizaje()) > 0) {
                            mat = materias.get(j);
                            materias.set(j, materias.get(j + 1));
                            materias.set(j + 1, mat);
                        }
                    }
                }

                break;
        }
    }

    public int busquedaBinariaRetID(String dato, String tipo) {
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "licenciatura":
                n = carreras.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (carreras.get(centro).getLicenciatura().equalsIgnoreCase(dato)) {
                        return Integer.parseInt(carreras.get(centro).getIdLicenciatura());
                    } else if (dato.compareToIgnoreCase(carreras.get(centro).getLicenciatura()) > 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
                break;
            case "grupo":
                n = grupos.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (grupos.get(centro).getNombreGrupo().equalsIgnoreCase(dato)) {
                        return Integer.valueOf(grupos.get(centro).getIdGrupo());
                    } else if (dato.compareToIgnoreCase(grupos.get(centro).getNombreGrupo()) < 0) {

                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
                break;
            case "periodo":
                n = periodos.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (periodos.get(centro).getPeriodo().equalsIgnoreCase(dato)) {
                        return Integer.valueOf(periodos.get(centro).getId_periodo());
                    } else if (dato.compareToIgnoreCase(periodos.get(centro).getPeriodo()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
                break;
            case "materia":
                n = materias.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (materias.get(centro).getUnidadAprendizaje().equalsIgnoreCase(dato)) {
                        return Integer.valueOf(materias.get(centro).getClaveMateria().replaceAll(" ", "").trim().trim());
                    } else if (dato.compareToIgnoreCase(materias.get(centro).getUnidadAprendizaje()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
                break;
        }
        return -1;
    }

    public String busquedaBinariaBuscaID(String id, String tipo) {
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "profesor":
                n = profes.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (profes.get(centro).getRfc().equalsIgnoreCase(id)) {
                        return profes.get(centro).getRfc();
                    } else if (id.compareToIgnoreCase(profes.get(centro).getRfc()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
                break;
            case "materia":
                n = materias.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (materias.get(centro).getClaveMateria().equalsIgnoreCase(id)) {
                        return materias.get(centro).getClaveMateria();
                    } else if (id.compareToIgnoreCase(materias.get(centro).getClaveMateria()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
                break;
        }
        return null;
    }

    public String busquedaBinariaRetNombre(int dato, String tipo) {
        ordenamientoBurbujaID("grupo");
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "licenciatura":
                n = carreras.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (Integer.parseInt(carreras.get(centro).getIdLicenciatura()) == dato) {
                        ordenamientoBurbujaNombre("grupo");
                        return carreras.get(centro).getLicenciatura();
                    } else if (dato < Integer.valueOf(carreras.get(centro).getIdLicenciatura())) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
            case "grupo":
                //ordenamientoBurbujaID("grupo");
                n = grupos.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (Integer.valueOf(grupos.get(centro).getIdGrupo()) == dato) {
                        return grupos.get(centro).getNombreGrupo();
                    } else if (dato < Integer.valueOf(grupos.get(centro).getIdGrupo())) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
        }
        ordenamientoBurbujaNombre("grupo");
        return "";
    }

    public void muestraHorarios(PeriodoHorarios horario) {
        System.out.println("Materia " + horario.getClaveMateria());
        System.out.println("RFC " + horario.getRfc());
        System.out.println("Grupo " + horario.getIdGrupo());
        System.out.println("Periodo " + horario.getIdPeriodo());
        System.out.println("Dia " + horario.getDia());
        System.out.println("Entrada " + horario.getEntrada());
        System.out.println("Salida " + horario.getSalida());
    }

    public String busquedaBinariaRetNombre(String dato, String tipo) {
        ordenamientoBurbujaID("materia");
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "materias":
                n = materias.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (materias.get(centro).getClaveMateria().equalsIgnoreCase(dato)) {
                        return materias.get(centro).getUnidadAprendizaje();
                    } else if (dato.compareToIgnoreCase(materias.get(centro).getClaveMateria()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
            case "profesores":
                n = profes.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (profes.get(centro).getRfc().equalsIgnoreCase(dato)) {
                        return profes.get(centro).getNombres() + " " + profes.get(centro).getApellidoP()  ;
                    } else if (dato.compareToIgnoreCase(profes.get(centro).getRfc()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
//            case "grupo":
//                n = grupos.size();
//                sup = n - 1;
//                while (inf <= sup) {
//                    centro = (sup + inf) / 2;
//                    if (Integer.valueOf(grupos.get(centro).getIdGrupo()) == dato) {
//                        return grupos.get(centro).getNombreGrupo();
//                    } else if (dato < Integer.valueOf(grupos.get(centro).getIdGrupo())) {
//                        sup = centro - 1;
//                    } else {
//                        inf = centro + 1;
//                    }
//                }
        }
        return "";
    }

}
