/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Archivo;
import Clases.ConectarBase;
import Clases.Conexion;
import Clases.ConsultasObjetos;
import Controlador.ControladorHorarios;
import Objetos.Grupo;
import Objetos.Licenciatura;
import Objetos.Materia;
import Objetos.PeriodoHorarios;
import Objetos.Profesor;
import Objetos.periodoEscolar;
import cjb.ci.Mensaje;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JeanCarlos
 */
public class VistaExcel extends javax.swing.JFrame {

    /**
     * Creates new form VistaExcel
     */
    public VistaExcel() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    File archivo;
    int numcorreo = 0;
    String cabeceras[];
    String tipoExcel = "";
    String cabecerasProfesor[] = {"rfc", "apellido paterno", "apellido materno", "nombre", "grado academico", "correo", "telefono"};
    String cabecerasMateria[] = {"clave de la materia", "unidad de aprendizaje", "horas", "creditos", "numero de periodo", "nucleo", "tipo", "licenciatura", "plan de estudios"};
    String cabecerasHorario[] = {"unidad_aprendizaje", "rfc", "profesor", "grupo", "periodo", "dia", "entrada", "salida"};
    ArrayList<Profesor> profes;
    ArrayList<Materia> materias;
    ArrayList<Grupo> grupos;
    ArrayList<Licenciatura> carreras;
    ArrayList<periodoEscolar> periodos;
    ArrayList<PeriodoHorarios> horarios;
    ArrayList<PeriodoHorarios> horariosBD;

    private File abrirArchivo() {
        String aux = "";
        String texto = "";
        String nombre = "";
        File abre = null;

        try {
            /**
             * llamamos el metodo que permite cargar la ventana
             */
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            nombre = file.getSelectedFile().getName();
            /**
             * abrimos el archivo seleccionado
             */

            abre = file.getSelectedFile();
            //Archivo.AbreArchivoV1(abre);
            return abre;
//
//            /**
//             * recorremos el archivo, lo leemos para plasmarlo en el area de texto
//             */
//            if (abre != null) {
//                FileReader archivos = new FileReader(abre);
//                BufferedReader lee = new BufferedReader(archivos);
//                while ((aux = lee.readLine()) != null) {
//                    texto += aux + "\n";
//                }
//                lee.close();
//            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
        return abre;
        //El texto se almacena en el JTextArea
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatosExcel = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtconsulta = new javax.swing.JTextArea();
        btnPrueba = new javax.swing.JButton();
        btnidentifica = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtidentifica = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnImportar.setBackground(new java.awt.Color(102, 102, 0));
        btnImportar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImportar.setForeground(new java.awt.Color(255, 255, 255));
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(102, 102, 0));
        btnExportar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        jTDatosExcel.setBackground(new java.awt.Color(25, 83, 0));
        jTDatosExcel.setForeground(new java.awt.Color(255, 255, 255));
        jTDatosExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTDatosExcel);

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cargar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtconsulta.setColumns(20);
        txtconsulta.setRows(5);
        jScrollPane2.setViewportView(txtconsulta);

        btnPrueba.setBackground(new java.awt.Color(102, 102, 0));
        btnPrueba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrueba.setForeground(new java.awt.Color(255, 255, 255));
        btnPrueba.setText("Prueba");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });

        btnidentifica.setBackground(new java.awt.Color(102, 102, 0));
        btnidentifica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnidentifica.setForeground(new java.awt.Color(255, 255, 255));
        btnidentifica.setText("Identifica");
        btnidentifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidentificaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtidentifica.setText("No identificado");

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar Celda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtidentifica, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(451, 451, 451))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(btnidentifica, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnidentifica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtidentifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        archivo = abrirArchivo();
        Archivo.Importar(archivo, jTDatosExcel);
        cabeceras = new String[jTDatosExcel.getColumnCount()];
        for (int i = 0; i < jTDatosExcel.getColumnCount(); i++) {
            cabeceras[i] = jTDatosExcel.getColumnName(i);
        }
        tipoExcel = identifica();
        txtidentifica.setText(tipoExcel);

    }//GEN-LAST:event_btnImportarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        importaBD();
        //muestraBD();
        ordenamientoBurbujaID("licenciatura");
        ordenamientoBurbujaNombre("materia");
        muestraBD();

        System.out.println("Busqueda " + busquedaBinariaRetID("INGENIERIA EN COMPUTACION", "licenciatura"));
        System.out.println("Busqueda " + busquedaBinariaRetNombre(6, "licenciatura"));

        System.out.println("Busqueda " + busquedaBinariaRetID("s2", "grupo"));
        System.out.println("Busqueda " + busquedaBinariaRetNombre(2, "grupo"));
        //txtidentifica.setForeground(Color.red);
        txtidentifica.setEditable(false);

    }//GEN-LAST:event_formWindowOpened

    public ArrayList<Object> extraeDatos() {
        ArrayList profesores = new ArrayList();

        for (int i = 0; i < jTDatosExcel.getRowCount(); i++) {
            Profesor profe = new Profesor();
            profe.setRfc(String.valueOf(jTDatosExcel.getValueAt(i, 0)));
            System.out.println(String.valueOf(jTDatosExcel.getValueAt(i, 0)));
            profe.setNombres((String) jTDatosExcel.getValueAt(i, 3));
            profe.setApellidoP((String) jTDatosExcel.getValueAt(i, 1));
            profe.setApellidoM((String) jTDatosExcel.getValueAt(i, 2));
            profe.setCorreo("no ingresado" + String.valueOf(numcorreo++));
            profe.setTelefono((String) jTDatosExcel.getValueAt(i, 6));
            profe.setGradoAcademico((String) jTDatosExcel.getValueAt(i, 2));
            profesores.add(profe);
        }
        return profesores;
    }

    public String identifica() {
        boolean identificado = false;
        if (cabeceras.length == cabecerasProfesor.length) {
            for (int i = 0; i < cabeceras.length; i++) {
                if (!cabeceras[i].equalsIgnoreCase(cabecerasProfesor[i])) {
                    break;
                }
            }
            txtconsulta.setText("Es un profesor");
            identificado = true;
            return "profesor";

        }
        if (cabeceras.length == cabecerasMateria.length && identificado) {
            for (int i = 0; i < cabeceras.length; i++) {
                if (!cabeceras[i].equalsIgnoreCase(cabecerasMateria[i])) {
                    break;
                }
            }
            identificado = true;
            return "materia";
        }

        if (cabeceras.length == cabecerasHorario.length) {
            for (int i = 0; i < cabeceras.length; i++) {
                if (!cabeceras[i].equalsIgnoreCase(cabecerasHorario[i])) {
                    break;
                }
            }
            identificado = true;
            return "horario";
        }
        if (!identificado) {
            return "No es encontro el tipo de excel";
        }
        return null;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        ArrayList horarios = guardaExcel();
//        ConsultasObjetos.insertaMuchos(horarios, ConectarBase.conectado(), "horarios");
        //        if (String.valueOf(jcTipo.getSelectedItem()).equals("Profesor")) {
//            
//        }
//            ArrayList<Object> profes= extraeDatos();
//            System.out.println(Controlador.ControladorProfesores.insertaMuchos(profes));
//txtconsulta.setText(ConsultasObjetos.retornaConsulta(profes, ConectarBase.conectado(), "profesores"));
//ConsultasObjetos.insertaMuchos(profes, ConectarBase.conectado(), "profesores");

    }//GEN-LAST:event_jButton2ActionPerformed

    public ArrayList guardaExcel() {

        if (tipoExcel.equalsIgnoreCase("horario")) {
            System.out.println("Entrando a horario");
            ArrayList horarios = new ArrayList();
            PeriodoHorarios horario;

            for (int i = 0; i < jTDatosExcel.getRowCount(); i++) {
                horario = new PeriodoHorarios();
                horario.setClaveMateria(String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 0)), "materia")));
                horario.setRfc(String.valueOf(String.valueOf(jTDatosExcel.getValueAt(i, 1))));
                if (ControladorHorarios.numdia(String.valueOf(jTDatosExcel.getValueAt(i, 5))) != 0) {
                    horario.setDia(String.valueOf(ControladorHorarios.numdia(String.valueOf(jTDatosExcel.getValueAt(i, 5)))));
                }
                horario.setIdGrupo(String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 3)), "grupo")));
                horario.setIdPeriodo(String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(i, 4)), "periodo")));
                horario.setEntrada(String.valueOf(jTDatosExcel.getValueAt(i, 6)));
                horario.setSalida(String.valueOf(jTDatosExcel.getValueAt(i, 7)));
                horarios.add(horario);
                muestraHorarios(horario);
            }
            return horarios;
        }
        return null;
    }

    public void importaBD() {
        materias = new ArrayList(ConsultasObjetos.consultaMuchos("materia", null, null, null, null, ConectarBase.conectado()));
        profes = new ArrayList(ConsultasObjetos.consultaMuchos("profesores", null, null, null, null, ConectarBase.conectado()));
        grupos = new ArrayList(ConsultasObjetos.consultaMuchos("grupo", null, null, null, null, ConectarBase.conectado()));
        carreras = new ArrayList(ConsultasObjetos.consultaMuchos("licenciatura", null, null, null, null, ConectarBase.conectado()));
        periodos = new ArrayList(ConsultasObjetos.consultaMuchos("periodo_escolar", null, null, null, null, ConectarBase.conectado()));
    }

    public void muestraBD() {
        for (Object materia : materias) {
            System.out.println(((Materia) materia).getUnidadAprendizaje());
        }
//        for (Object profesor : profes){
//            System.out.println(((Profesor)profesor).getNombres());
//        }
        for (Object grupo : grupos) {
            System.out.println(((Grupo) grupo).getNombreGrupo());
        }
        for (Object licen : carreras) {
            System.out.println(((Licenciatura) licen).getLicenciatura());
        }
        for (Object periodo : periodos) {
            System.out.println(((periodoEscolar) periodo).getPeriodo());
        }
    }

    public void transforma() {

    }


    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        Archivo.Exportar(jTDatosExcel, "horario", "prueba1");
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
        for (int i = 0; i < cabeceras.length; i++) {
            System.out.println("Cabecera numero " + i + ": " + cabeceras[i]);
        }
    }//GEN-LAST:event_btnPruebaActionPerformed

    private void btnidentificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidentificaActionPerformed

    }//GEN-LAST:event_btnidentificaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (tipoExcel.equalsIgnoreCase("horario")) {

            horarios = guardaExcel();
            horariosBD = new ArrayList(ConsultasObjetos.consultaMuchos("horarios", "id_grupo", String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(0, 3)), "grupo")),
                    "id_periodo", String.valueOf(busquedaBinariaRetID(String.valueOf(jTDatosExcel.getValueAt(0, 4)), "periodo")), ConectarBase.conectado()));
            System.out.println("hasta aqui llego");
        }

        comparaGrupos();

    }//GEN-LAST:event_jButton1ActionPerformed

    public void comparaGrupos() {
        txtconsulta.setText("");
        double entrada1, salida1, entrada2, salida2;
        for (int i = 0; i < horarios.size(); i++) {
            for (int j = 0; j < horarios.size(); j++) {
                //System.out.println("dia: "+horarios.get(i).getDia() + " ---->"+ "dia: "+horarios.get(j).getDia() );

                if (horarios.get(i).getDia().equals(horarios.get(j).getDia()) && i != j && horarios.get(i).getIdGrupo().equals(horarios.get(j).getIdGrupo())) {
                    //System.out.println("Mismo dia ");
                    //System.out.println(horarios.get(i).getClaveMateria() + " " + horarios.get(i).getRfc() + " " + horarios.get(i).getIdPeriodo());
                    //System.out.println(horarios.get(j).getClaveMateria() + " " + horarios.get(j).getRfc() + " " + horarios.get(j).getIdPeriodo());
                    entrada1 = Double.parseDouble(horarios.get(i).getEntrada().substring(0, 2) + "." + horarios.get(i).getEntrada().substring(3, 5));
                    salida1 = Double.parseDouble(horarios.get(i).getSalida().substring(0, 2) + "." + horarios.get(i).getSalida().substring(3, 5));
                    entrada2 = Double.parseDouble(horarios.get(j).getEntrada().substring(0, 2) + "." + horarios.get(j).getEntrada().substring(3, 5));
                    salida2 = Double.parseDouble(horarios.get(j).getSalida().substring(0, 2) + "." + horarios.get(j).getSalida().substring(3, 5));
                    if (entrada2 >= entrada1 && entrada2 <= salida1) {
                        txtconsulta.setText(txtconsulta.getText() + "Error Por grupos\n"
                                + String.valueOf(jTDatosExcel.getValueAt(i, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 5)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 7))
                                + " y "
                                + String.valueOf(jTDatosExcel.getValueAt(j, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(j, 5)) + " " + String.valueOf(jTDatosExcel.getValueAt(j, 6)) + " " + String.valueOf(jTDatosExcel.getValueAt(j, 7)) + "\n\n");
                        //System.out.println("horarios cruzados");
                    }
                }
            }
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTDatosExcel.getSelectedRow() != -1) {
            ((DefaultTableModel) jTDatosExcel.getModel()).removeRow(jTDatosExcel.getSelectedRow());
        } else {
            Mensaje.error(this, "No se pudo eliminar la celda");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        evaluaProfesores();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void evaluaProfesores() {
        txtconsulta.setText("");
        double entrada1, entrada2, salida1, salida2;
        horariosBD = new ArrayList(ConsultasObjetos.consultaMuchos("horarios", null, null, null, null, ConectarBase.conectado()));
        horarios = guardaExcel();

        for (int i = 0; i < horarios.size(); i++) {
            for (int j = 0; j < horariosBD.size(); j++) {
                //System.out.println("i: "+i);
                //System.out.println("j: "+j);
                if (horarios.get(i).getRfc().equalsIgnoreCase(horariosBD.get(j).getRfc()) && horarios.get(i).getDia().equals(horariosBD.get(j).getDia())) {

                    entrada1 = Double.parseDouble(horarios.get(i).getEntrada().substring(0, 2) + "." + horarios.get(i).getEntrada().substring(3, 5));
                    salida1 = Double.parseDouble(horarios.get(i).getSalida().substring(0, 2) + "." + horarios.get(i).getSalida().substring(3, 5));
                    entrada2 = Double.parseDouble(horariosBD.get(j).getEntrada().substring(0, 2) + "." + horariosBD.get(j).getEntrada().substring(3, 5));
                    salida2 = Double.parseDouble(horariosBD.get(j).getSalida().substring(0, 2) + "." + horariosBD.get(j).getSalida().substring(3, 5));
                    System.out.println("horario1 " + entrada1 + " " + salida1);
                    System.out.println("horario2 " + entrada2 + " " + salida2);
                    System.out.println("mismo dia ");
                    if (entrada2 >= entrada1 && entrada2 <= salida1) {
                        txtconsulta.setText(txtconsulta.getText() + "Error Por Profesores\n"
                                + String.valueOf(jTDatosExcel.getValueAt(i, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 5)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 6)) + " " + String.valueOf(jTDatosExcel.getValueAt(i, 7))
                                + " y "
                                + busquedaBinariaRetNombre(horariosBD.get(j).getClaveMateria(), "materias") + "-> " + ControladorHorarios.numdia(Integer.valueOf(horariosBD.get(j).getDia())) + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida() + "\n\n");

                        System.out.println("Profesor: " + String.valueOf(jTDatosExcel.getValueAt(i, 2)) + "cruzado " + horarios.get(i).getDia() + " " + horarios.get(i).getEntrada() + " " + horarios.get(i).getSalida());
                        System.out.println("Con id: " + horariosBD.get(j).getIdHorario() + " " + horariosBD.get(j).getDia() + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida());

                        //txtconsulta.setText(txtconsulta.getText() + "Error en Grupos: " + String.valueOf(jTDatosExcel.getValueAt(i, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + " y " + String.valueOf(jTDatosExcel.getValueAt(j, 0)) + " -> " + String.valueOf(jTDatosExcel.getValueAt(i, 3)) + "\n\n");
                        //System.out.println("horarios cruzados");
                    }

//                    System.out.println("ProfesorLoc:" + horarios.get(i).getDia() + " " + horarios.get(i).getEntrada() + " " + horarios.get(i).getSalida());
//                    System.out.println("ProfesorBD:" + horariosBD.get(j).getDia() + " " + horariosBD.get(j).getEntrada() + " " + horariosBD.get(j).getSalida());
                }
            }
        }

        System.out.println("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaExcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExportar;
    public javax.swing.JButton btnImportar;
    private javax.swing.JButton btnPrueba;
    private javax.swing.JButton btnidentifica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTDatosExcel;
    private javax.swing.JTextArea txtconsulta;
    private javax.swing.JTextField txtidentifica;
    // End of variables declaration//GEN-END:variables

    public void ordenamientoBurbujaID(String tipo) {
        switch (tipo) {
            case "grupo":
                Grupo grup;
                for (int i = 2; i < grupos.size(); i++) {
                    for (int j = 0; j < grupos.size() - i; j++) {
                        if (Integer.valueOf(grupos.get(j).getIdGrupo()) > Integer.valueOf(grupos.get(j + 1).getIdGrupo())) {
                            grup = grupos.get(j);
                            grupos.set(j, grupos.get(j + 1));
                            grupos.set(j + 1, grup);
                        }
                    }
                }
                break;
            case "licenciatura":
                Licenciatura lic;
                for (int i = 2; i < carreras.size(); i++) {
                    for (int j = 0; j < carreras.size() - i; j++) {
                        if (carreras.get(j).getIdLicenciatura().compareToIgnoreCase(carreras.get(j + 1).getIdLicenciatura()) > 0) {
                            lic = carreras.get(j);
                            carreras.set(j, carreras.get(j + 1));
                            carreras.set(j + 1, lic);
                        }
                    }
                }
                break;

            case "materia":
                Materia mat;
                for (int i = 2; i < materias.size(); i++) {
                    for (int j = 0; j < materias.size() - i; j++) {
                        if (materias.get(j).getClaveCarrera().compareToIgnoreCase(materias.get(j + 1).getClaveCarrera()) > 0) {
                            mat = materias.get(j);
                            materias.set(j, materias.get(j + 1));
                            materias.set(j + 1, mat);
                        }
                    }
                }

                break;
        }
    }

    public void ordenamientoBurbujaNombre(String tipo) {
        switch (tipo) {
            case "grupo":
                Grupo grup;
                for (int i = 2; i < grupos.size(); i++) {
                    for (int j = 0; j < grupos.size() - i; j++) {
                        if (grupos.get(j).getNombreGrupo().compareToIgnoreCase(grupos.get(j + 1).getNombreGrupo()) > 0) {
                            grup = grupos.get(j);
                            grupos.set(j, grupos.get(j + 1));
                            grupos.set(j + 1, grup);
                        }
                    }
                }
                break;
            //esta por id
            case "licenciatura":
                Licenciatura lic;
                for (int i = 2; i < carreras.size(); i++) {
                    for (int j = 0; j < carreras.size() - i; j++) {
                        if (carreras.get(j).getIdLicenciatura().compareToIgnoreCase(carreras.get(j + 1).getIdLicenciatura()) > 0) {
                            lic = carreras.get(j);
                            carreras.set(j, carreras.get(j + 1));
                            carreras.set(j + 1, lic);
                        }
                    }
                }
                break;

            case "materia":
                Materia mat;
                for (int i = 2; i < materias.size(); i++) {
                    for (int j = 0; j < materias.size() - i; j++) {
                        if (materias.get(j).getUnidadAprendizaje().compareToIgnoreCase(materias.get(j + 1).getUnidadAprendizaje()) > 0) {
                            mat = materias.get(j);
                            materias.set(j, materias.get(j + 1));
                            materias.set(j + 1, mat);
                        }
                    }
                }

                break;
        }
    }

    public int busquedaBinariaRetID(String dato, String tipo) {
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "licenciatura":
                n = carreras.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (carreras.get(centro).getLicenciatura().equalsIgnoreCase(dato)) {
                        return Integer.parseInt(carreras.get(centro).getIdLicenciatura());
                    } else if (dato.compareToIgnoreCase(carreras.get(centro).getLicenciatura()) > 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
            case "grupo":
                n = grupos.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (grupos.get(centro).getNombreGrupo().equalsIgnoreCase(dato)) {
                        return Integer.valueOf(grupos.get(centro).getIdGrupo());
                    } else if (dato.compareToIgnoreCase(grupos.get(centro).getNombreGrupo()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
            case "periodo":
                n = periodos.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (periodos.get(centro).getPeriodo().equalsIgnoreCase(dato)) {
                        return Integer.valueOf(grupos.get(centro).getIdGrupo());
                    } else if (dato.compareToIgnoreCase(periodos.get(centro).getPeriodo()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
            case "materia":
                n = materias.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (materias.get(centro).getUnidadAprendizaje().equalsIgnoreCase(dato)) {
                        return Integer.valueOf(materias.get(centro).getClaveMateria().replaceAll(" ", "").trim().trim());
                    } else if (dato.compareToIgnoreCase(materias.get(centro).getUnidadAprendizaje()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
        }
        return -1;
    }

    public String busquedaBinariaRetNombre(int dato, String tipo) {
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "licenciatura":
                n = carreras.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (Integer.parseInt(carreras.get(centro).getIdLicenciatura()) == dato) {
                        return carreras.get(centro).getLicenciatura();
                    } else if (dato < Integer.valueOf(carreras.get(centro).getIdLicenciatura())) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
            case "grupo":
                n = grupos.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (Integer.valueOf(grupos.get(centro).getIdGrupo()) == dato) {
                        return grupos.get(centro).getNombreGrupo();
                    } else if (dato < Integer.valueOf(grupos.get(centro).getIdGrupo())) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
        }
        return "";
    }

    public void muestraHorarios(PeriodoHorarios horario) {
        System.out.println("Materia " + horario.getClaveMateria());
        System.out.println("RFC " + horario.getRfc());
        System.out.println("Grupo " + horario.getIdGrupo());
        System.out.println("Periodo " + horario.getIdPeriodo());
        System.out.println("Dia " + horario.getDia());
        System.out.println("Entrada " + horario.getEntrada());
        System.out.println("Salida " + horario.getSalida());
    }
    
        public String busquedaBinariaRetNombre(String dato, String tipo) {
        ordenamientoBurbujaID("materia");
        int n, inf = 0, sup, centro;
        switch (tipo) {
            case "materias":
                n = materias.size();
                sup = n - 1;
                while (inf <= sup) {
                    centro = (sup + inf) / 2;
                    if (materias.get(centro).getClaveMateria().equalsIgnoreCase(dato)) {
                        return materias.get(centro).getClaveMateria();
                    } else if (dato.compareToIgnoreCase(materias.get(centro).getClaveMateria()) < 0) {
                        sup = centro - 1;
                    } else {
                        inf = centro + 1;
                    }
                }
//            case "grupo":
//                n = grupos.size();
//                sup = n - 1;
//                while (inf <= sup) {
//                    centro = (sup + inf) / 2;
//                    if (Integer.valueOf(grupos.get(centro).getIdGrupo()) == dato) {
//                        return grupos.get(centro).getNombreGrupo();
//                    } else if (dato < Integer.valueOf(grupos.get(centro).getIdGrupo())) {
//                        sup = centro - 1;
//                    } else {
//                        inf = centro + 1;
//                    }
//                }
        }
        return "";
    }

}
